---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: egress-router-cni-nad
  namespace: "{{.EgressRouterNamespace}}"
  annotations:
    release.openshift.io/version: "{{.ReleaseVersion}}"
spec:
  config: '{
    "cniVersion": "0.4.0",
    "type": "egress-router",
    "name": "egress-router-cni-nad",
    "ip": {
      "addresses": [
        "{{.Addresses}}/24"
        ],
      "destinations": [
      {{range $i, $val := .AllowedDestinations}}{{if $i}},{{end}}{{if and ($val.Port) ($val.Protocol)}}{{if $val.TargetPort}}"{{$val.Port}} {{$val.Protocol}} {{$val.DestinationIP}}/30 {{$val.TargetPort}}"{{else}}"{{$val.Port}} {{$val.Protocol}} {{$val.DestinationIP}}/30"{{end}}{{else}}"{{$val.DestinationIP}}/30"{{end}}{{end}}
        ],
      "gateway": "{{.Gateway}}"
        },
      "log_file": "/tmp/egress-router-log",
      "log_level": "debug"
      }'